# Generated by Django 3.1.1 on 2020-09-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('company_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('profile_picture', models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to='users/client/%Y/%m/%d/')),
            ],
        ),
    ]
