# Generated by Django 3.1.1 on 2020-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
