# Generated by Django 3.1.1 on 2020-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0002_auto_20200915_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
