# Generated by Django 3.1.1 on 2020-09-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0003_client_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
    ]
