# Generated by Django 3.1.1 on 2020-09-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0006_auto_20200915_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
