# Generated by Django 3.1.1 on 2020-09-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_team_description'),
        ('adminusers', '0008_auto_20200915_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Assigned'), (3, 'In Progress'), (4, 'Completed')], default=1)),
                ('team_leader_notified', models.BooleanField(default=False)),
                ('submission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminusers.project')),
            ],
        ),
    ]
