# Generated by Django 3.1.1 on 2020-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0009_auto_20200916_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='assigned_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
