# Generated by Django 3.1.1 on 2020-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0011_auto_20200917_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
