# Generated by Django 3.1.1 on 2020-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0012_project_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
