# Generated by Django 3.1.1 on 2020-09-19 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0016_auto_20200919_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Assigned'), (3, 'Running'), (4, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Assigned'), (3, 'Running'), (4, 'Submitted to QA'), (5, 'Completed')], default=1),
        ),
        migrations.CreateModel(
            name='SubmittedToQATask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('qa_team_notified', models.BooleanField(default=False)),
                ('submitted_at', models.DateField(default=datetime.datetime(2020, 9, 19, 7, 2, 2, 867999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminusers.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
