# Generated by Django 3.1.1 on 2020-09-19 01:16

import adminusers.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0017_auto_20200919_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtoqatask',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to=adminusers.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 7, 16, 25, 277383)),
        ),
    ]
