# Generated by Django 3.1.1 on 2020-09-19 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0019_auto_20200919_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_to_qa_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 8, 38, 0, 376140)),
        ),
    ]
