# Generated by Django 3.1.1 on 2020-09-19 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_team_is_qa_team'),
        ('adminusers', '0020_auto_20200919_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtoqatask',
            name='qa_team',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 19, 50, 4, 749882)),
        ),
    ]
