# Generated by Django 3.1.1 on 2020-09-19 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminusers', '0022_auto_20200919_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedtoqatask',
            name='qa_team',
        ),
        migrations.AddField(
            model_name='submittedtoqatask',
            name='qa_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 21, 26, 11, 756763)),
        ),
    ]
