# Generated by Django 3.1.1 on 2020-09-19 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0023_auto_20200919_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedtoqatask',
            old_name='qa_member',
            new_name='tester',
        ),
        migrations.RenameField(
            model_name='submittedtoqatask',
            old_name='qa_team_notified',
            new_name='tester_notified',
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Running'), (3, 'Verified')], default=1),
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 22, 42, 34, 194578)),
        ),
    ]
