# Generated by Django 3.1.1 on 2020-09-19 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminusers', '0024_auto_20200919_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_send_to_qa_team',
            new_name='is_send_tester',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='submitted_to_qa_at',
            new_name='submitted_to_tester_at',
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 22, 53, 32, 349415)),
        ),
    ]
