# Generated by Django 3.1.1 on 2020-09-10 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('leader', models.ManyToManyField(blank=True, related_name='team_leader_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='team_member_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
