# Generated by Django 3.1.1 on 2020-10-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.SET_DEFAULT, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
