# Generated by Django 3.1.1 on 2020-09-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200910_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
