# Generated by Django 3.1.1 on 2020-09-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200911_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
