# Generated by Django 3.1.1 on 2020-09-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200912_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
