# Generated by Django 3.1.1 on 2020-09-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20200912_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
