# Generated by Django 3.1.1 on 2020-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_qa_team',
            field=models.BooleanField(default=False),
        ),
    ]
