# Generated by Django 3.1.1 on 2020-10-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201003_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_role', to='accounts.role'),
        ),
    ]
