# Generated by Django 3.1.1 on 2020-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
