# Generated by Django 3.1.1 on 2020-09-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_description'),
        ('accounts', '0006_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_department', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='user_role', to='accounts.role'),
        ),
    ]
