# Generated by Django 3.1.1 on 2020-09-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20200913_0745'),
        ('accounts', '0007_auto_20200911_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_member',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
        ),
    ]
