# Generated by Django 3.1.1 on 2020-09-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
