# Generated by Django 3.1.1 on 2020-10-03 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201003_2119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='assigned_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project'),
        ),
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='assigned_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.module'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.module'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='submitted_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.submittedtoqatask'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.task'),
        ),
    ]
