# Generated by Django 3.1.1 on 2020-10-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_module_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtoqatask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.task'),
        ),
    ]
