# Generated by Django 3.1.1 on 2020-10-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_project_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
