# Generated by Django 3.1.1 on 2020-09-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='notification',
            field=models.IntegerField(default=0),
        ),
    ]
